function(subdirs result start_dir)
    file(GLOB children RELATIVE ${start_dir} ${start_dir}/*)
    set(dirlist "")
    foreach(child ${children})
        if(IS_DIRECTORY ${start_dir}/${child})
            LIST(APPEND dirlist ${start_dir}/${child})
        endif()
    endforeach()
    set(${result} ${dirlist} PARENT_SCOPE)
endfunction()